module.exports = {
  'Accept Cookies': '[data-test-id="cookie-acceptance-btn"]',
  'GA - Book Me': '[data-test-id="release-card-action__book-general-attendee"]',
  'Payment Loader': '[data-test-id="payment-loader"]',
  'Customer details': '[data-test-id="checkout-heading"]',
  'Customer details -> First name': '[data-test-id="payment-form__first-name"]',
  'Customer details -> Last name': '[data-test-id="payment-form__last-name"]',
  'Customer details -> Email': '[data-test-id="payment-form__email"]',
  'Customer details -> Address': '[data-test-id="payment-form__line1"]',
  'Customer details -> Country dropdown': '[data-test-id="checkout-heading"] [role="combobox"]',
  'Customer details -> Country dropdown -> Portugal': '[data-test-id="country-select-Portugal"]',
  'Customer details -> City': '[data-test-id="payment-form__city"]',
  'Customer details -> Postal Code': '[data-test-id="payment-form__postal-code"]',
  'Payment -> Pay with stripe': '[data-test-id="pay-with-stripe"]',
  'Payment -> Pay with paypal': '[data-test-id="pay-with-paypal"]',
  'Payment -> Card number': '[data-test-id="stripe__card-number"] iframe input[data-elements-stable-field-name="cardNumber"]',
  'Payment -> Expiry date': '[data-test-id="stripe__expiry-date"] iframe input[data-elements-stable-field-name="cardExpiry"]',
  'Payment -> CVV': '[data-test-id="stripe__cvv"] iframe input[data-elements-stable-field-name="cardCvc"]',
  'Payment -> Accept T&Cs': '[data-test-id="payment-form__t-and-c"]',
  'Payment -> Pay securely now': '[data-test-id="pay-now-button"]',
  'Payment -> Card error': '#StripePaymentForm__cardNumber-helper-text',
  'Paypal -> Username': '#email',
  'Paypal -> Accept Cookies': '#acceptAllButton',
  'Paypal -> Next': '#btnNext',
  'Paypal -> Password': '#password',
  'Paypal -> Login': '#btnLogin',
  'Paypal -> Loading': '[data-testid="loading-svg"]',
  'Paypal -> Confirm Payment': '#payment-submit-btn',
  'Success page': '[data-test-id="payment-success-message"]',
  'Notification': '.MuiSnackbar-root',
};
